---
- hosts: lampservers
  gather_facts: true
  become: true

  roles:
    - packages     # prerequisites for MediaWiki Setup
    - mediawiki    # Download and Installation of Mediawiki
    - config       # Post-Install Configuration for Apache/FW/Security
#    - ssh_deploy    ## Can be added as role if required -- Ansible initial configurations and setup

## For OS distribution specific variables
#  tasks:
  # - name: Gather OS distribution specific variables
  #   include_vars: "{{ item }}"
  #   with_first_found:
  #     - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
  #     - "{{ ansible_distribution }}.yml"
  #   tags: vars
