---
# tasks file for config

# Post Configuration changes for Apache, Firewall and SELinux

- name: Change Document root directory and Index in httpd.conf 
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DocumentRoot "/var/www"', line: 'DocumentRoot "/var/www/mediawiki"' }
    - { regexp: '^<Directory "/var/www">', line: '<Directory "/var/www/mediawiki">' }
    - { regexp: '^DirectoryIndex', line: 'DirectoryIndex index.html index.html.var index.php' }
  notify: restart httpd

- name: install firewalld if not present
  dnf:
    name: firewalld
    state: present

- name: Firewall Configuration
  firewalld:
    service: "{{ item }}"
    permanent: yes
    zone: public
    state: enabled
  with_items:
    - http
    - https
  notify: restart firewalld

- name: SELinux Configuration
  shell: getenforce
  register: result

- name: Set Context
  command: restorecon -FR /var/www/"{{ item }}"
  with_items:
    - mediawiki-1.34.2
    - mediawiki
  when: result.stdout == "Enforcing"

- name: Change owner to apache:apache user
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: apache
    group: apache
  with_items:
    - /var/www/mediawiki
    - /var/www/{{ mediawiki_tar_name }}
  notify: restart httpd

# - name: Validate context
#   command: ls -lZ /var/www/
#   register: result
#   debug: msg="{{ result.stdout }}"
